# buffer_sweep/timeloop_sweep.py
"""Timeloop-scheduled SRAM partition sweep.

Division of labor (spec: docs/superpowers/specs/2026-07-06-timeloop-sweep-design.md):
  * WE sweep the architecture DOF: how the SRAM cap is partitioned into the
    W / A / O dedicated spaces (each ping-pong x2, so the mapper sees half).
  * TIMELOOP (WSL, timeloop-mapper) searches the schedule per (partition, GEMM):
    tile sizes + loop permutation, quantized by the 32x32 spatial SA.
  * OUR evaluator scores the returned mapping for the FINAL numbers: bit-serial
    timing (x WBITS), ping-pong prefetch windows, psum spill/reload, and the
    project energy coefficients. Timeloop's internal EDP only ranks its search.

Pipeline (all idempotent, disk-cached under results/tl_cache/):
  gen   -> write arch.yaml+problem.yaml per missing (partition, GEMM-shape) job
  run   -> one WSL call: timeloop/run_jobs.sh runs all pending jobs in parallel
  score -> parse map.yaml per job, eval with eval_nest(), aggregate per model,
           write CSV + heatmaps + summary plots under results/timeloop/

eval_nest() generalizes buffer_sweep.walk_gemm to an arbitrary Timeloop loop
nest: per-operand tiles can differ (multi-level M splits etc.), O tiles may be
evicted mid-accumulation (spill 32b + reload 32b), and each operand's next-tile
prefetch is spread over the CURRENT tile's residency interval (the shadow copy
is free for exactly that long). For the v1 O-stationary nest this reduces
EXACTLY to walk_gemm (asserted by --selftest); the one deliberate difference is
v1's Kt==1 corner, where v1 conservatively charged the whole W fetch to a
single step window (new model spreads it; selftest asserts traffic equal and
new steady <= v1 steady).

Usage:
  python timeloop_sweep.py --selftest
  python timeloop_sweep.py --quick               # deit_tiny x 64KB x few partitions
  python timeloop_sweep.py                       # full: all models x 64/128/256KB
  python timeloop_sweep.py --score-only          # skip mapper, score cached jobs
"""
import argparse
import csv
import hashlib
import math
import os
import re
import subprocess

import buffer_sweep as bs

HERE = os.path.dirname(os.path.abspath(__file__))
TL_DIR = os.path.join(HERE, "timeloop")
OUT_DIR = os.path.join(HERE, "results", "timeloop")

SLICES = 6              # partition grid: cap/2 split into this many slices
JOBS = 3                # parallel mapper jobs inside WSL


def _cache_dir():
    """Job cache keyed by the mapper config: editing mapper_sweep.yaml starts a
    fresh cache subdir (stale results from other knobs are never mixed in)."""
    with open(os.path.join(TL_DIR, "mapper_sweep.yaml"), "rb") as f:
        tag = hashlib.md5(f.read().replace(b"\r\n", b"\n")).hexdigest()[:8]
    return os.path.join(HERE, "results", "tl_cache", "cfg_" + tag)


CACHE_DIR = _cache_dir()

# Fixed architectural level order, outer to inner (matches arch.yaml chain).
LEVELS = ("DRAM", "w_buffer", "a_buffer", "o_buffer")
SPATIAL = {"K": 32, "N": 32}          # SA: row=K, col=N (M temporal)
# operand -> (home level, projected dims). Timeloop dataspace names in ():
# W=(A), A=(B), O=(Z).
OPERANDS = {
    "W": ("w_buffer", ("M", "K"), bs.WBITS),
    "A": ("a_buffer", ("K", "N"), bs.ABITS),
    "O": ("o_buffer", ("M", "N"), bs.OBITS),
}

ARCH_TEMPLATE = """architecture:
  # generated by timeloop_sweep.py -- do not edit by hand (edit the template)
  version: 0.4
  nodes:
  - !Container
    name: system
    attributes: {{technology: "45nm", global_cycle_seconds: 1e-9}}
  - !Component
    name: DRAM
    class: DRAM
    attributes: {{type: "LPDDR4", width: 64, datawidth: 8}}
  - !Container
    name: gemm_accel
    attributes: {{technology: "45nm"}}
  - !Parallel
    nodes:
    - !Component
      name: w_buffer
      class: smartbuffer_SRAM
      attributes: {{depth: {w_depth}, width: 8, datawidth: 8}}
      constraints: {{dataspace: {{keep: [A], bypass: [B, Z]}}}}
    - !Component
      name: a_buffer
      class: smartbuffer_SRAM
      attributes: {{depth: {a_depth}, width: 8, datawidth: 8}}
      constraints: {{dataspace: {{keep: [B], bypass: [A, Z]}}}}
    - !Component
      name: o_buffer
      class: smartbuffer_SRAM
      attributes: {{depth: {o_depth}, width: 32, datawidth: 32}}
      constraints: {{dataspace: {{keep: [Z], bypass: [A, B]}}}}
  - !Container
    name: PE
    spatial: {{meshX: 32, meshY: 32}}
    constraints:
      spatial: {{permutation: [M, K, N], split: 2, factors: [K=32, N=32, M=1]}}
  - !Component
    name: mac
    class: intmac
    attributes: {{multiplier_width: 8, adder_width: 32}}
"""

PROBLEM_TEMPLATE = """problem:
  version: 0.4
  instance: {{M: {M}, K: {K}, N: {N}}}
  shape:
    name: gemm_ABZ
    dimensions: [M, N, K]
    data_spaces:
    - name: A
      projection: [[[M]], [[K]]]
    - name: B
      projection: [[[N]], [[K]]]
    - name: Z
      projection: [[[M]], [[N]]]
      read_write: true
"""


# ----------------------------------------------------------------------------
# map.yaml mini-parser (stdlib only -- no yaml module needed for this shape)
# ----------------------------------------------------------------------------
def parse_map_yaml(text):
    """Return {level: [(dim, factor), ...] outer->inner} for the temporal loops
    of the four LEVELS. map.yaml lists `permutation` INNERMOST-FIRST and
    `factors: M4 N1 K6`; unit factors are placeholders and dropped."""
    entries = {}
    cur = None
    for line in text.splitlines():
        s = line.strip()
        m = re.match(r"- target: (\w+)", s)
        if m:
            cur = {"target": m.group(1), "type": None, "factors": None, "perm": None}
            continue
        if cur is None:
            continue
        m = re.match(r"type: (\w+)", s)
        if m:
            cur["type"] = m.group(1)
        m = re.match(r"factors: (.+)", s)
        if m:
            cur["factors"] = m.group(1).strip()
        m = re.match(r"permutation: (\w+)", s)
        if m:
            cur["perm"] = m.group(1).strip()
        if cur["type"] and (cur["type"] == "datatype" or (cur["factors"] and cur["perm"])):
            if cur["type"] in ("temporal", "spatial"):
                entries[(cur["target"], cur["type"])] = (cur["factors"], cur["perm"])
            cur = None if cur["type"] != "datatype" else cur  # datatype: wait for end
    levels = {}
    for lv in LEVELS:
        fac, perm = entries.get((lv, "temporal"), ("M1 N1 K1", "MNK"))
        fmap = {}
        for tok in fac.split():
            fmap[tok[0]] = int(tok[1:])
        loops = [(d, fmap.get(d, 1)) for d in reversed(perm)]   # outer -> inner
        levels[lv] = [(d, f) for (d, f) in loops if f > 1]
    # spatial sanity: the SA constraint must have been respected
    fac, _perm = entries.get(("inter_PE_spatial", "spatial"), (None, None))
    if fac:
        sfac = {tok[0]: int(tok[1:]) for tok in fac.split()}
        if sfac.get("K", 1) != 32 or sfac.get("N", 1) != 32:
            raise ValueError("mapping violates 32x32 spatial constraint: %s" % fac)
    return levels


def nest_str(levels):
    """Compact one-line nest for CSV/console, e.g. 'DRAM:M7 | w:N24 | a:M8 | o:M4.K6'."""
    tag = {"DRAM": "DRAM", "w_buffer": "w", "a_buffer": "a", "o_buffer": "o"}
    parts = []
    for lv in LEVELS:
        if levels[lv]:
            parts.append(tag[lv] + ":" + ".".join("%s%d" % (d, f) for d, f in levels[lv]))
    return " | ".join(parts) if parts else "(all-resident)"


def parse_stats(text):
    """Timeloop's own Summary Stats -> (cycles, energy_uJ). Sanity columns only."""
    cyc = re.search(r"^Cycles: (\d+)", text, re.M)
    en = re.search(r"^Energy: ([0-9.eE+-]+) uJ", text, re.M)
    if not cyc or not en:
        raise ValueError("could not parse Summary Stats")
    return int(cyc.group(1)), float(en.group(1))


# ----------------------------------------------------------------------------
# Generalized evaluator: walk an arbitrary nest (our cost semantics)
# ----------------------------------------------------------------------------
def synthetic_nest(M, K, N, m, k, n, perm="MNK"):
    """v1-style single-tile nest: DRAM loops (perm outer->inner over tile
    counts), tiles (m,k,n) realized below the buffers. Dims must divide."""
    Mp, Kp, Np = bs.pad32(M), bs.pad32(K), bs.pad32(N)
    assert Mp % m == 0 and Kp % k == 0 and Np % n == 0, "synthetic nest needs divisors"
    counts = {"M": Mp // m, "K": Kp // k, "N": Np // n}
    return {
        "DRAM": [(d, counts[d]) for d in perm if counts[d] > 1],
        "w_buffer": [],
        "a_buffer": [],
        "o_buffer": [(d, f) for d, f in
                     (("M", m), ("K", k // 32), ("N", n // 32)) if f > 1],
    }


def eval_nest(levels, M, K, N, bw=None):
    """Score one mapping under OUR cost semantics. Returns the walk_gemm dict
    (reads/writes bits, fill, steady, drain, compute) -- see module docstring.

    Steps = one iteration of the temporal loops ABOVE o_buffer (loops at
    o_buffer + spatial live inside every operand's tile). All steps are uniform
    (Timeloop factorizes the padded dims exactly), so intervals collapse to
    closed-form demand segments."""
    bw = bs.EFF_BW if bw is None else bw
    Mp, Kp, Np = bs.pad32(M), bs.pad32(K), bs.pad32(N)
    dims = {"M": Mp, "K": Kp, "N": Np}
    # validate factorization: product over all levels + spatial == padded dims
    for d in "MKN":
        prod = SPATIAL.get(d, 1)
        for lv in LEVELS:
            for (dd, f) in levels[lv]:
                if dd == d:
                    prod *= f
        if prod != dims[d]:
            raise ValueError("nest does not factorize %s: %d != %d" % (d, prod, dims[d]))

    # operand tile sizes: product of its dims' factors at home level and below
    tile_bits = {}
    for op, (home, odims, obits) in OPERANDS.items():
        hi = LEVELS.index(home)
        elems = 1
        for d in odims:
            p = SPATIAL.get(d, 1)
            for lv in LEVELS[hi:]:
                for (dd, f) in levels[lv]:
                    if dd == d:
                        p *= f
            elems *= p
        tile_bits[op] = elems * obits

    # step loops = everything above o_buffer, outer -> inner
    step_loops = []              # (dim, factor, level_idx)
    for li, lv in enumerate(LEVELS[:3]):
        for (d, f) in levels[lv]:
            step_loops.append((d, f, li))
    T = 1
    for (_d, f, _li) in step_loops:
        T *= f
    macs_per_step = (Mp * Kp * Np) // T
    comp = bs.CYCLES_PER_BIT * bs.WBITS * macs_per_step / (bs.TILE * bs.TILE)
    compute = bs.CYCLES_PER_BIT * bs.WBITS * Mp * Kp * Np / (bs.TILE * bs.TILE)

    # id positions per operand: loops strictly ABOVE its home that project on it
    idpos = {}
    for op, (home, odims, _b) in OPERANDS.items():
        hi = LEVELS.index(home)
        idpos[op] = [i for i, (d, _f, li) in enumerate(step_loops)
                     if li < hi and d in odims]
    kpos = [i for i, (d, _f, _li) in enumerate(step_loops) if d == "K"]
    k_req = 1
    for i in kpos:
        k_req *= step_loops[i][1]

    # walk the odometer once, recording per-operand residency intervals
    coords = [0] * len(step_loops)
    intervals = {op: [] for op in OPERANDS}     # (start, oid)
    o_kseen = []                                # per O interval: set of k-coords
    prev = {op: None for op in OPERANDS}
    for t in range(T):
        for op in OPERANDS:
            oid = tuple(coords[i] for i in idpos[op])
            if oid != prev[op]:
                intervals[op].append([t, oid])
                if op == "O":
                    o_kseen.append(set())
                prev[op] = oid
        if kpos:
            o_kseen[-1].add(tuple(coords[i] for i in kpos))
        # increment odometer (innermost = last position fastest)
        for i in range(len(step_loops) - 1, -1, -1):
            coords[i] += 1
            if coords[i] < step_loops[i][1]:
                break
            coords[i] = 0
        else:
            pass                                # T exhausted anyway
    if not kpos:
        for s in o_kseen:
            s.add(())

    def lens(iv):
        return [(iv[i + 1][0] if i + 1 < len(iv) else T) - iv[i][0]
                for i in range(len(iv))]

    # O bookkeeping: spill (departs incomplete) / reload (arrives after spill)
    o_iv = intervals["O"]
    o_len = lens(o_iv)
    seen = {}
    spilled = set()
    reload_flag = [False] * len(o_iv)
    complete_flag = [False] * len(o_iv)
    for i, (_s, oid) in enumerate(o_iv):
        if oid in spilled:
            reload_flag[i] = True
        seen.setdefault(oid, set()).update(o_kseen[i])
        if len(seen[oid]) == k_req:
            complete_flag[i] = True             # departs complete (final write)
        else:
            spilled.add(oid)                    # departs partial (spill write)
    assert all(len(s) == k_req for s in seen.values()), "O accumulation incomplete"

    # traffic (bits)
    n_w, n_a, n_o = len(intervals["W"]), len(intervals["A"]), len(o_iv)
    n_reload = sum(reload_flag)
    reads = n_w * tile_bits["W"] + n_a * tile_bits["A"] + n_reload * tile_bits["O"]
    writes = n_o * tile_bits["O"]               # every departure writes (spill|final)

    # per-step DRAM demand, piecewise constant on merged interval segments:
    #   W/A: NEXT tile prefetch spread over the CURRENT tile's interval
    #   O:   predecessor drain + (spilled) successor reload over current interval
    def demands(op):
        iv, ln, out = intervals[op], lens(intervals[op]), []
        for i in range(len(iv)):
            if op == "O":
                bits = (tile_bits["O"] if i > 0 else 0.0) \
                     + (tile_bits["O"] if i + 1 < len(iv) and reload_flag[i + 1] else 0.0)
            else:
                bits = tile_bits[op] if i + 1 < len(iv) else 0.0
            out.append((iv[i][0], bits / ln[i]))
        return out                              # (start, demand_per_step)

    dmd = {op: demands(op) for op in OPERANDS}
    breakpoints = sorted({0, T} | {s for op in OPERANDS for (s, _d) in dmd[op]})
    ptr = {op: 0 for op in OPERANDS}
    steady = 0.0
    for bi in range(len(breakpoints) - 1):
        b0, b1 = breakpoints[bi], breakpoints[bi + 1]
        d = 0.0
        for op in OPERANDS:
            lst = dmd[op]
            while ptr[op] + 1 < len(lst) and lst[ptr[op] + 1][0] <= b0:
                ptr[op] += 1
            d += lst[ptr[op]][1]
        steady += max(0.0, d / bw - comp) * (b1 - b0)

    fill = (tile_bits["W"] + tile_bits["A"]) / bw
    drain = tile_bits["O"] / bw                 # last final write, nothing hides it
    return {"reads": float(reads), "writes": float(writes), "fill": fill,
            "steady": steady, "drain": drain, "compute": compute,
            "tile_bits": dict(tile_bits), "n_fetch": (n_w, n_a, n_o, n_reload)}


def rollup(M, K, N, r):
    """eval_nest result -> energy/cycles with the v1 coefficients (single source:
    same formulas as buffer_sweep.gemm_cost, generalized reads/writes)."""
    Mp, Kp, Np = bs.pad32(M), bs.pad32(K), bs.pad32(N)
    cubes = (Mp // bs.TILE) * (Kp // bs.TILE) * (Np // bs.TILE)
    dram = r["reads"] + r["writes"]
    onchip = r["reads"] + cubes * bs.TILE * bs.TILE * (bs.ABITS + bs.WBITS)
    mac = Mp * Kp * Np
    rmw = cubes * bs.TILE * bs.TILE
    energy = (dram * bs.C_DRAM + onchip * bs.C_ONCHIP
              + mac * bs.C_MAC + rmw * bs.C_RMW)
    cycles = r["compute"] + r["fill"] + r["steady"] + r["drain"]
    return {"energy": energy, "cycles": cycles, "dram_bits": dram,
            "steady": r["steady"]}


# ----------------------------------------------------------------------------
# Sweep bookkeeping
# ----------------------------------------------------------------------------
def model_shapes(model):
    """Aggregate a model's per-layer GEMMs into {(Mp,Kp,Np): weight}."""
    spec = bs.MODELS[model]
    out = {}
    for (_g, M, K, N, cnt) in spec["gemms"]:
        key = (bs.pad32(M), bs.pad32(K), bs.pad32(N))
        out[key] = out.get(key, 0) + cnt * spec["layers"]
    return out


def partitions(cap_kb, slices=SLICES):
    """Split the per-copy budget (cap/2, ping-pong) into (W,A,O) bit triples on
    a slices-grid, each >= 1 slice. Returns [(w_bits, a_bits, o_bits), ...]."""
    half = cap_kb * 1024 * 8 // 2
    assert half % slices == 0
    unit = half // slices
    out = []
    for wi in range(1, slices - 1):
        for ai in range(1, slices - wi):
            oi = slices - wi - ai
            out.append((wi * unit, ai * unit, oi * unit))
    return out


def job_key(shape, part):
    (M, K, N), (wb, ab, ob) = shape, part
    return "M%dK%dN%d_w%d_a%d_o%d" % (M, K, N, wb // 8, ab // 8, ob // 32)


def gen_jobs(models, caps, slices):
    """Write arch/problem YAMLs for every missing (partition, shape) job."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    keys = set()
    for cap in caps:
        for part in partitions(cap, slices):
            for model in models:
                for shape in model_shapes(model):
                    keys.add((shape, part))
    n_new = 0
    for (shape, part) in sorted(keys):
        key = job_key(shape, part)
        d = os.path.join(CACHE_DIR, key)
        if os.path.isdir(d):
            continue
        os.makedirs(d)
        (M, K, N), (wb, ab, ob) = shape, part
        with open(os.path.join(d, "arch.yaml"), "w", newline="\n") as f:
            f.write(ARCH_TEMPLATE.format(w_depth=wb // 8, a_depth=ab // 8,
                                         o_depth=ob // 32))
        with open(os.path.join(d, "problem.yaml"), "w", newline="\n") as f:
            f.write(PROBLEM_TEMPLATE.format(M=M, K=K, N=N))
        n_new += 1
    print("gen_jobs: %d total, %d newly generated" % (len(keys), n_new))
    return len(keys)


def to_wsl(path):
    p = os.path.abspath(path).replace("\\", "/")
    return "/mnt/" + p[0].lower() + p[2:]


def run_jobs(jobs=JOBS, deadline=240):
    """One blocking WSL call that runs every pending job (parallel inside)."""
    cmd = "%s %s %d %d" % (to_wsl(os.path.join(TL_DIR, "run_jobs.sh")),
                           to_wsl(CACHE_DIR), jobs, deadline)
    print("run_jobs: wsl bash -lc '%s'" % cmd)
    r = subprocess.run(["wsl", "bash", "-lc", cmd])
    if r.returncode != 0:
        raise RuntimeError("run_jobs.sh failed (exit %d)" % r.returncode)


def load_job(shape, part):
    """Cached mapper result -> (levels, tl_cycles, tl_energy_uj) or None if the
    mapper found no valid mapping for this partition."""
    d = os.path.join(CACHE_DIR, job_key(shape, part))
    if os.path.isfile(os.path.join(d, "INVALID")):
        return None
    with open(os.path.join(d, "map.yaml")) as f:
        levels = parse_map_yaml(f.read())
    with open(os.path.join(d, "stats.txt")) as f:
        tl_cyc, tl_uj = parse_stats(f.read())
    return levels, tl_cyc, tl_uj


# ----------------------------------------------------------------------------
# v1 baseline: best O-stationary (m,k,n) under the same partition
# ----------------------------------------------------------------------------
_V1_MEMO = {}


def v1_best(model, part):
    """Best v1 (grouped, O-stationary) energy/cycles fitting (w,a,o) bit caps.
    v1 semantics (residual tiles allowed; Kt==1 stall charged conservatively)."""
    wb, ab, ob = part
    shapes = model_shapes(model)
    max_m = max(M for (M, _K, _N) in shapes)
    max_k = max(K for (_M, K, _N) in shapes)
    max_n = max(N for (_M, _K, N) in shapes)
    best = None
    m = bs.TILE
    while m <= max_m and bs.WBITS * m * bs.TILE <= wb and bs.OBITS * m * bs.TILE <= ob:
        k = bs.TILE
        while k <= max_k and bs.WBITS * m * k <= wb and bs.ABITS * k * bs.TILE <= ab:
            n = bs.TILE
            while (n <= max_n and bs.ABITS * k * n <= ab
                   and bs.OBITS * m * n <= ob):
                tot_e = tot_c = 0.0
                for (M, K, N), wgt in shapes.items():
                    ck = (M, K, N, m, k, n)
                    c = _V1_MEMO.get(ck)
                    if c is None:
                        c = bs.gemm_cost(M, K, N, m, k, n)
                        _V1_MEMO[ck] = c
                    tot_e += c["energy"] * wgt
                    tot_c += c["cycles"] * wgt
                if best is None or (tot_e, tot_c) < (best[0], best[1]):
                    best = (tot_e, tot_c, m, k, n)
                n += bs.TILE
            k += bs.TILE
        m += bs.TILE
    return best          # None if nothing fits


# ----------------------------------------------------------------------------
# Scoring + outputs
# ----------------------------------------------------------------------------
def score(models, caps, slices, top=5):
    os.makedirs(OUT_DIR, exist_ok=True)
    all_rows = []
    for model in models:
        shapes = model_shapes(model)
        rows = []
        details = []
        for cap in caps:
            for part in partitions(cap, slices):
                wb, ab, ob = part
                tot = {"energy": 0.0, "cycles": 0.0, "dram_bits": 0.0,
                       "steady": 0.0, "tl_cycles": 0.0, "tl_uj": 0.0}
                bad = None
                for shape, wgt in sorted(shapes.items()):
                    job = load_job(shape, part)
                    if job is None:
                        bad = shape
                        break
                    levels, tl_cyc, tl_uj = job
                    M, K, N = shape
                    r = rollup(M, K, N, eval_nest(levels, M, K, N))
                    for kk in ("energy", "cycles", "dram_bits", "steady"):
                        tot[kk] += r[kk] * wgt
                    tot["tl_cycles"] += tl_cyc * wgt
                    tot["tl_uj"] += tl_uj * wgt
                    details.append({
                        "model": model, "cap_kb": cap,
                        "w_kb": wb * 2 // 8192, "a_kb": ab * 2 // 8192,
                        "o_kb": ob * 2 // 8192,
                        "shape": "%dx%dx%d" % shape, "weight": wgt,
                        "nest": nest_str(levels),
                        "energy_pj": r["energy"], "cycles": r["cycles"],
                        "tl_cycles": tl_cyc, "tl_energy_uj": tl_uj,
                    })
                v1 = v1_best(model, part)
                row = {
                    "model": model, "cap_kb": cap,
                    "w_kb": wb * 2 // 8192, "a_kb": ab * 2 // 8192,
                    "o_kb": ob * 2 // 8192,          # physical KB incl. ping-pong
                    "feasible": bad is None,
                    "energy_pj": tot["energy"] if bad is None else math.nan,
                    "cycles": tot["cycles"] if bad is None else math.nan,
                    "steady_stall": tot["steady"] if bad is None else math.nan,
                    "tl_cycles_sum": tot["tl_cycles"] if bad is None else math.nan,
                    "tl_energy_uj_sum": tot["tl_uj"] if bad is None else math.nan,
                    "v1_energy_pj": v1[0] if v1 else math.nan,
                    "v1_cycles": v1[1] if v1 else math.nan,
                    "v1_mkn": ("%d/%d/%d" % (v1[2], v1[3], v1[4])) if v1 else "",
                    "fail_shape": ("%dx%dx%d" % bad) if bad else "",
                }
                # best known = min(timeloop-proposed, v1 floor), per metric
                cands = []
                if bad is None:
                    cands.append(("tl", tot["energy"], tot["cycles"]))
                if v1:
                    cands.append(("v1", v1[0], v1[1]))
                if cands:
                    be = min(cands, key=lambda c: c[1])
                    bc = min(cands, key=lambda c: c[2])
                    row.update(best_energy_pj=be[1], best_energy_src=be[0],
                               best_cycles=bc[2], best_cycles_src=bc[0])
                    row["feasible"] = True       # at least one scheduler fits
                else:
                    row.update(best_energy_pj=math.nan, best_energy_src="",
                               best_cycles=math.nan, best_cycles_src="")
                rows.append(row)
        all_rows += rows
        _write_csv(rows, os.path.join(OUT_DIR, "%s.csv" % model))
        _write_csv(details, os.path.join(OUT_DIR, "%s_details.csv" % model))
        _console(rows, model, caps, top)
        for cap in caps:
            for metric, tag in (("best_energy_pj", "energy"), ("best_cycles", "cycles")):
                _plot_partition_heatmap(
                    rows, model, cap, metric, slices,
                    os.path.join(OUT_DIR, "%s_cap%d_%s.png" % (model, cap, tag)))
    for metric, tag in (("best_energy_pj", "energy"), ("best_cycles", "cycles")):
        _plot_summary(all_rows, caps, metric,
                      os.path.join(OUT_DIR, "summary_%s.png" % tag))
    print("score: wrote CSVs and plots to %s" % OUT_DIR)
    return all_rows


def _write_csv(rows, path):
    if not rows:
        return
    with open(path, "w", newline="") as f:
        wr = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        wr.writeheader()
        wr.writerows(rows)


def _console(rows, model, caps, top):
    for cap in caps:
        sub = [r for r in rows if r["cap_kb"] == cap and r["feasible"]]
        n_all = sum(1 for r in rows if r["cap_kb"] == cap)
        print("%s  cap=%dKB  (%d/%d partitions feasible)"
              % (model, cap, len(sub), n_all))
        if not sub:
            continue
        sub.sort(key=lambda r: (r["best_energy_pj"], r["best_cycles"]))
        print("  %5s %5s %5s %13s %12s %4s %13s %13s"
              % ("W/KB", "A/KB", "O/KB", "best_E(uJ)", "best_cyc(M)", "src",
                 "tl_E(uJ)", "v1_E(uJ)"))
        for r in sub[:top]:
            def _uj(x):
                return (x / 1e6) if not math.isnan(x) else float("nan")
            print("  %5d %5d %5d %13.3f %12.3f %4s %13.3f %13.3f"
                  % (r["w_kb"], r["a_kb"], r["o_kb"],
                     r["best_energy_pj"] / 1e6, r["best_cycles"] / 1e6,
                     r["best_energy_src"], _uj(r["energy_pj"]),
                     _uj(r["v1_energy_pj"])))
        byc = min(sub, key=lambda r: (r["best_cycles"], r["best_energy_pj"]))
        print("  best-by-cycles: W=%d A=%d O=%d KB  cycles=%.3fM (src=%s)  energy=%.3fuJ\n"
              % (byc["w_kb"], byc["a_kb"], byc["o_kb"],
                 byc["best_cycles"] / 1e6, byc["best_cycles_src"],
                 byc["best_energy_pj"] / 1e6))


def _plot_partition_heatmap(rows, model, cap, metric, slices, out_path):
    plt = bs._plt()
    sub = [r for r in rows if r["cap_kb"] == cap and r["feasible"]]
    if plt is None or not sub:
        return False
    unit_kb = cap / slices
    grid = [[math.nan] * (slices - 1) for _ in range(slices - 1)]
    for r in sub:
        wi = int(round(r["w_kb"] / unit_kb)) - 1
        ai = int(round(r["a_kb"] / unit_kb)) - 1
        grid[wi][ai] = r[metric]
    best = min(sub, key=lambda r: r[metric])
    fig, ax = plt.subplots(figsize=(5.5, 4.5))
    im = ax.imshow(grid, origin="lower", aspect="auto",
                   extent=[unit_kb / 2, cap - unit_kb / 2,
                           unit_kb / 2, cap - unit_kb / 2])
    ax.plot(best["a_kb"], best["w_kb"], "r*", markersize=15)
    ax.set_xlabel("A space (KB, incl. ping-pong)")
    ax.set_ylabel("W space (KB, incl. ping-pong)")
    ax.set_title("%s cap=%dKB %s (star: W=%d A=%d O=%d)"
                 % (model, cap, metric, best["w_kb"], best["a_kb"], best["o_kb"]))
    fig.colorbar(im, ax=ax, shrink=0.85)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)
    return True


def _plot_summary(all_rows, caps, metric, out_path):
    plt = bs._plt()
    if plt is None or not all_rows:
        return False
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    v1_metric = {"best_energy_pj": "v1_energy_pj", "best_cycles": "v1_cycles"}[metric]
    plotted = False
    for model in sorted({r["model"] for r in all_rows}):
        xs, ys, yv = [], [], []
        for cap in caps:
            sub = [r for r in all_rows
                   if r["model"] == model and r["cap_kb"] == cap and r["feasible"]]
            if sub:
                xs.append(cap)
                ys.append(min(r[metric] for r in sub))
                vv = [r[v1_metric] for r in sub if not math.isnan(r[v1_metric])]
                yv.append(min(vv) if vv else math.nan)
        if not xs:
            continue                        # no feasible partition anywhere
        plotted = True
        line, = ax.plot(xs, ys, marker="o", label=model + " (best known)")
        vpts = [(x, v) for x, v in zip(xs, yv) if not math.isnan(v)]
        if vpts:
            ax.plot([x for x, _v in vpts], [v for _x, v in vpts], marker="x",
                    linestyle="--", color=line.get_color(), alpha=0.6,
                    label=model + " (v1 fixed)")
    if not plotted:
        plt.close(fig)
        return False
    ax.set_xlabel("SRAM cap (KB, incl. ping-pong)")
    ax.set_ylabel("best " + metric)
    ax.set_yscale("log")
    ax.set_xscale("log", base=2)
    ax.legend(fontsize=7)
    ax.grid(True, which="both", alpha=0.3)
    fig.tight_layout()
    fig.savefig(out_path, dpi=110)
    plt.close(fig)
    return True


# ----------------------------------------------------------------------------
# Selftest
# ----------------------------------------------------------------------------
def selftest():
    n = 0
    # 1. v1 equivalence: O-stationary synthetic nest == buffer_sweep.walk_gemm
    #    (exact, divisor tiles, Kt >= 2 so every W/A interval is one step)
    for (M, K, N) in ((64, 64, 64), (128, 96, 64), (224, 192, 96)):
        for (m, k, nn) in ((32, 32, 32), (64, 32, 32), (32, 32, 64)):
            if M % m or K % k or N % nn or K // k < 2:
                continue
            for bw in (1.0, bs.EFF_BW, 1e9):
                a = bs.walk_gemm(M, K, N, m, k, nn, bw)
                b = eval_nest(synthetic_nest(M, K, N, m, k, nn), M, K, N, bw)
                for key in ("fill", "steady", "drain", "compute"):
                    assert math.isclose(a[key], b[key], rel_tol=1e-9, abs_tol=1e-6), \
                        (key, M, K, N, m, k, nn, bw, a[key], b[key])
                assert math.isclose(a["reads"], b["reads"]) \
                    and math.isclose(a["writes"], b["writes"])
                n += 1
    # 2. Kt == 1 corner: traffic identical; new interval-spread stall <= v1's
    for bw in (1.0, bs.EFF_BW):
        a = bs.walk_gemm(96, 64, 128, 32, 64, 32, bw)
        b = eval_nest(synthetic_nest(96, 64, 128, 32, 64, 32), 96, 64, 128, bw)
        assert math.isclose(a["reads"], b["reads"]) and math.isclose(a["writes"], b["writes"])
        assert b["steady"] <= a["steady"] + 1e-9
        n += 1
    # 3. psum spill hand-check: K OUTERMOST at DRAM forces spill+reload
    lv = {"DRAM": [("K", 2), ("M", 2), ("N", 2)], "w_buffer": [],
          "a_buffer": [], "o_buffer": [("M", 32)]}    # tiles 32x32x32
    r = eval_nest(lv, 64, 64, 64, bw=1e9)
    tw, ta, to = 32 * 32 * bs.WBITS, 32 * 32 * bs.ABITS, 32 * 32 * bs.OBITS
    assert r["n_fetch"] == (4, 8, 8, 4), r["n_fetch"]   # W ivs, A ivs, O ivs, reloads
    assert r["reads"] == 4 * tw + 8 * ta + 4 * to
    assert r["writes"] == 8 * to                        # 4 spills + 4 finals
    assert r["steady"] == 0.0                           # bw=1e9 hides everything
    n += 1
    # 4. smoke-run mapping reproduction (skipped if output/ not present locally)
    smoke = os.path.join(TL_DIR, "output", "timeloop-mapper.map.yaml")
    if os.path.isfile(smoke):
        with open(smoke) as f:
            levels = parse_map_yaml(f.read())
        r = eval_nest(levels, 224, 192, 768)
        # Timeloop's own element counts for this mapping (NOTES.md section b):
        assert r["reads"] == (43008 + 7 * 147456) * 8, r["reads"]
        assert r["writes"] == 172032 * 32
        assert r["steady"] == 0.0                       # interval-spread hides all
        with open(os.path.join(TL_DIR, "output", "timeloop-mapper.stats.txt")) as f:
            assert parse_stats(f.read()) == (32256, 321.03)
        n += 1
    print("timeloop_sweep selftest OK (%d checks)" % n)
    return 0


# ----------------------------------------------------------------------------
def main(argv=None):
    p = argparse.ArgumentParser(description="Timeloop-scheduled SRAM partition sweep")
    p.add_argument("--models", default="all")
    p.add_argument("--caps", default="64,128,256")
    p.add_argument("--slices", type=int, default=SLICES)
    p.add_argument("--jobs", type=int, default=JOBS)
    p.add_argument("--deadline", type=int, default=240,
                   help="per-job mapper wall-clock (s); SIGINT dumps best-so-far")
    p.add_argument("--score-only", action="store_true",
                   help="skip the WSL mapper stage; score cached jobs only")
    p.add_argument("--quick", action="store_true",
                   help="deit_tiny x 64KB x 4 slices (pipeline smoke)")
    p.add_argument("--selftest", action="store_true")
    a = p.parse_args(argv)
    if a.selftest:
        return selftest()

    models = sorted(bs.MODELS) if a.models == "all" else a.models.split(",")
    for m in models:
        if m not in bs.MODELS:
            p.error("unknown model %r" % m)
    try:
        caps = [int(x) for x in a.caps.split(",")]
    except ValueError as e:
        p.error("--caps must be comma-separated integers (%s)" % e)
    slices = a.slices
    if a.quick:
        models, caps, slices = ["deit_tiny"], [64], 4

    gen_jobs(models, caps, slices)
    if not a.score_only:
        run_jobs(a.jobs, a.deadline)
    score(models, caps, slices)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
